# Generated by Django 5.1.2 on 2024-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_target',
            field=models.IntegerField(),
        ),
    ]
